# Generated by Django 5.0.4 on 2024-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_doacao', models.DateTimeField()),
                ('produtos', models.JSONField()),
                ('documento', models.CharField(max_length=14)),
            ],
        ),
    ]
