# Generated by Django 5.0.4 on 2024-06-05 01:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='data_doacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
