# Generated by Django 5.0.4 on 2024-06-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doacao_data_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='local_destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
